runtime: plugin
action:
  title: Compose
  description: Fetch and merge packages from compose.yaml
  options:
    - name: working-dir
      shorthand: w
      title: Working directory
      description: Working directory for temp files
      type: string
      default: .plasma/model/compose/packages
    - name: skip-not-versioned
      shorthand: s
      title: Skip unversioned
      description: Skip not versioned files from source directory (git only)
      type: boolean
      default: false
    - name: conflicts-verbosity
      title: Conflicts verbosity
      description: Log files conflicts
      type: boolean
      default: false
    - name: clean
      title: Clean
      description: Remove .plasma/model/compose dir on start
      type: boolean
      default: false
    - name: interactive
      title: Interactive
      description: Interactive mode allows to submit user credentials during action
      type: boolean
      default: true
  result:
    type: object
    properties:
      status:
        type: string
